# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671592c1270aeae1a78a5957abada92029d254d0b4b2ea15b3dc1ddfeeb4cdb274ee0cf930e34af9a77de52fa0f77107def36507dd5b73dbbe2d83ace9b895b2

test:
  secret_key_base: 8e92f2f144c81d0c0c6a7db84ee062b26e58d3487b7262600724c2fbba17a174c3a7836913af7c706ef904153bebbbd0c3a6b64ff1cea140a590e8b197220e61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
